//
//  Workspace.swift
//  memo_tuistManifests
//
//  Created by mincheol on 2022/12/14.
//

import ProjectDescription

let workspace = Workspace(
  name: "Memo",
  projects: [
    "Projects/**"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: true,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant)
  )
)
