name: Memo CI

on: 
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: Run CI
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Tuist generate
        uses: tuist/tuist-action@0.13.0
        with: 
          command: 'generate'
          arguments: ''

      - name: Build
        run: |
          set -o pipefail && xcodebuild \
            -workspace Memo.xcworkspace \
            -scheme Memo-Dev \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 13' \
            -quiet \
            build      
      
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
            -workspace Memo.xcworkspace \
            -scheme Memo-Workspace \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 13' \
            -resultBundlePath TestResults \
            -quiet \
            test
      
      - name: Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
